"""
Motet - Artifact Commands

Copyright (c) 2024-2026 Motet Contributors
Licensed under the Functional Source License, Version 1.1, or a commercial license. See LICENSE.

Author: Matt Chisholm <matt@motet.dev>
Last Modified: 2026-08-24

Description:
    Distributed commands for artifact lifecycle operations.
    Centralizes artifact creation logic (store + optional derivation dispatch) so it can be reused
    across HTTP APIs, CLI flows, tool-produced artifacts, and background ingestion jobs.

Dependencies:
    - motet.core.artifacts: Artifact store and ArtifactKind types
    - motet.core.commands.decorator / motet: @motet.command and MotetContext access
    - motet.core.commands.command_data_classes: CreateArtifactData
    - motet.core.commands.builtin.derivation: text, image, and office media derivation commands
    - structlog: Structured logging

Usage:
    from motet.core.commands.builtin.artifacts import create_artifact
    from motet.core.commands.command_data_classes import CreateArtifactData

    cmd = create_artifact(
        task_id="task-123",
        conversation_id="conv-123",
        tenant_id="tenant",
        principal_id="principal",
        motet_id="default",
        data=CreateArtifactData(
            payload=b"...",
            content_type="application/pdf",
            kind="user_upload",
            filename="doc.pdf",
            trigger_derivations=True,
        ),
    )
"""

from __future__ import annotations

from typing import Any, Dict, List

import structlog

from motet import motet
from motet.core.commands.decorator import get_motet_context
from motet.core.commands.capabilities import WorkerCapability
from motet.core.commands.command_data_classes import (
    CreateArtifactData,
    DeriveOfficeEmbeddedImagesData,
    DeriveUploadImageData,
    DeriveUploadTextData,
    DeriveVideoTranscriptData,
    DeriveVideoVisualsData,
)
from motet.core.commands.builtin.derivation import (
    derive_office_embedded_images,
    derive_upload_image,
    derive_upload_text,
    derive_video_transcript,
    derive_video_visuals,
)

logger = structlog.get_logger(__name__)


@motet.command(
    description="Create and store an artifact (upload or generated bytes) and optionally trigger derivation pipelines.",
    timeout_seconds=60,
    required_capabilities=[WorkerCapability.FILE_OPERATIONS],
)
def create_artifact(data: CreateArtifactData) -> Dict[str, Any]:
    """
    Create an artifact and (optionally) trigger derivations.

    Notes:
        - Derivations are dispatched fire-and-forget (non-blocking).
        - This command is intentionally opinionated: it applies the same derivation trigger policy everywhere.
    """
    motet = get_motet_context()

    from motet.core.artifacts import ArtifactKind
    from motet.core.media.derivation_policy import get_eligible_derivations

    content_type = (data.content_type or "application/octet-stream").strip()
    if isinstance(data.payload, bytes):
        try:
            from motet.core.media.image_processing import detect_image_content_type_from_bytes

            detected_content_type = detect_image_content_type_from_bytes(
                data.payload,
                fallback=content_type,
            )
            if detected_content_type != content_type:
                logger.info(
                    "artifact_content_type_corrected",
                    supplied_content_type=content_type,
                    detected_content_type=detected_content_type,
                    filename=data.filename,
                )
                content_type = detected_content_type
        except Exception as e:
            logger.warning(
                "artifact_content_type_detection_failed",
                supplied_content_type=content_type,
                filename=data.filename,
                error=str(e),
            )

    # Conversation scoping: use motet helper for consistent resolution
    conversation_id = motet.resolve_conversation_id(data.conversation_id)

    metadata: Dict[str, Any] = dict(data.metadata or {})
    if data.prep_hints:
        ph = data.prep_hints
        metadata["prep_hints"] = ph.model_dump(exclude_none=True)
        if ph.prep_strategy_id:
            metadata["prep_strategy_id"] = ph.prep_strategy_id
        if ph.disable_strategies:
            metadata["disable_strategies"] = list(ph.disable_strategies)
    if data.filename:
        metadata.setdefault("filename", data.filename)
        metadata.setdefault("original_filename", data.filename)
    if conversation_id:
        metadata.setdefault("conversation_id", conversation_id)

    try:
        kind_enum = ArtifactKind(str(data.kind))
    except Exception:
        kind_enum = ArtifactKind.USER_UPLOAD

    payload_len = len(data.payload or b"")
    logger.info(
        "create_artifact_started",
        **motet.log_fields(
            content_type=content_type,
            kind=str(kind_enum.value),
            bytes=payload_len,
            conversation_id=conversation_id,
        )
    )

    artifact_id = motet.artifact_store.put(
        payload=data.payload,
        content_type=content_type,
        kind=kind_enum,
        metadata=metadata,
        ttl_seconds=data.ttl_seconds,
    )

    dispatched: List[Dict[str, Any]] = []
    if data.trigger_derivations:
        # Use centralized derivation eligibility logic
        eligible = get_eligible_derivations(
            content_type,
            kind=str(kind_enum.value),
            include_text_for_json=data.include_text_derivation_for_json,
        )

        if "text" in eligible:
            model_provider = str(metadata.get("model_provider") or "").strip() or None
            model_name = str(metadata.get("model_name") or "").strip() or None
            model_profile_name = str(metadata.get("model_profile_name") or "").strip() or None
            child = derive_upload_text(
                task_id=motet.task_id or "",
                conversation_id=conversation_id,
                tenant_id=motet.tenant_id,
                principal_id=motet.principal_id,
                motet_id=motet.motet_id,
                data=DeriveUploadTextData(
                    source_artifact_id=artifact_id,
                    model_provider=model_provider,
                    model_name=model_name,
                    model_profile_name=model_profile_name,
                ),
            )
            try:
                task_ids = motet.dispatch([child])
            except Exception:
                task_ids = []
            dispatched.append({"type": "text", "child_command_id": child.command_id, "task_ids": task_ids})

        if "embedded_images" in eligible:
            model_provider = str(metadata.get("model_provider") or "").strip() or None
            model_name = str(metadata.get("model_name") or "").strip() or None
            model_profile_name = str(metadata.get("model_profile_name") or "").strip() or None
            child = derive_office_embedded_images(
                task_id=motet.task_id or "",
                conversation_id=conversation_id,
                tenant_id=motet.tenant_id,
                principal_id=motet.principal_id,
                motet_id=motet.motet_id,
                data=DeriveOfficeEmbeddedImagesData(
                    source_artifact_id=artifact_id,
                    image_derivation_names=["thumb", "base"],
                    model_provider=model_provider,
                    model_name=model_name,
                    model_profile_name=model_profile_name,
                ),
            )
            try:
                task_ids = motet.dispatch([child])
            except Exception:
                task_ids = []
            dispatched.append({"type": "embedded_images", "child_command_id": child.command_id, "task_ids": task_ids})

        if "image" in eligible:
            derivation_names = data.image_derivation_names or ["thumb", "base", "detail"]
            child = derive_upload_image(
                task_id=motet.task_id or "",
                conversation_id=conversation_id,
                tenant_id=motet.tenant_id,
                principal_id=motet.principal_id,
                motet_id=motet.motet_id,
                data=DeriveUploadImageData(
                    source_artifact_id=artifact_id,
                    derivation_names=derivation_names,
                ),
            )
            try:
                task_ids = motet.dispatch([child])
            except Exception:
                task_ids = []
            dispatched.append({"type": "image", "child_command_id": child.command_id, "task_ids": task_ids})

        if "video" in eligible:
            # ADR-0119: visuals and transcript derive in parallel — independent
            # routing, retries, and completion events for the two tracks.
            visuals_child = derive_video_visuals(
                task_id=motet.task_id or "",
                conversation_id=conversation_id,
                tenant_id=motet.tenant_id,
                principal_id=motet.principal_id,
                motet_id=motet.motet_id,
                data=DeriveVideoVisualsData(source_artifact_id=artifact_id),
            )
            transcript_child = derive_video_transcript(
                task_id=motet.task_id or "",
                conversation_id=conversation_id,
                tenant_id=motet.tenant_id,
                principal_id=motet.principal_id,
                motet_id=motet.motet_id,
                data=DeriveVideoTranscriptData(source_artifact_id=artifact_id),
            )
            try:
                task_ids = motet.dispatch([visuals_child, transcript_child])
            except Exception:
                task_ids = []
            dispatched.append(
                {"type": "video_visuals", "child_command_id": visuals_child.command_id, "task_ids": task_ids}
            )
            dispatched.append(
                {"type": "video_transcript", "child_command_id": transcript_child.command_id, "task_ids": task_ids}
            )

        cfg = getattr(getattr(motet, "stack", None), "config", None)
        if bool(getattr(cfg, "artifact_rag_enabled", False)) and content_type == "application/json":
            from motet.core.commands.command_data_classes import PrepareArtifactIndexData
            from motet.core.commands.builtin.rag import prepare_artifact_index

            child = prepare_artifact_index(
                task_id=motet.task_id or "",
                conversation_id=conversation_id,
                tenant_id=motet.tenant_id,
                principal_id=motet.principal_id,
                motet_id=motet.motet_id,
                data=PrepareArtifactIndexData(
                    source_artifact_id=artifact_id,
                    strategy_id=data.prep_hints.prep_strategy_id if data.prep_hints else None,
                    force_reindex=True,
                ),
            )
            try:
                task_ids = motet.dispatch([child])
            except Exception:
                task_ids = []
            dispatched.append({"type": "prep_index", "child_command_id": child.command_id, "task_ids": task_ids})

    logger.info(
        "create_artifact_completed",
        **motet.log_fields(
            artifact_id=artifact_id,
            content_type=content_type,
            kind=str(kind_enum.value),
            bytes=payload_len,
            derivations_dispatched=len(dispatched),
        )
    )

    return {
        "artifact_id": artifact_id,
        "content_type": content_type,
        "kind": str(kind_enum.value),
        "bytes": payload_len,
        "derivations": dispatched,
    }


